# Generated by Django 4.0.4 on 2023-03-07 18:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Dados_Cadastro_PENF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_cadastro', models.CharField(max_length=50, verbose_name='Categoria_Cadastro')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data_Cadastro')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=600, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Pais_Usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pais', models.CharField(max_length=100, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculo', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Telefone_Usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data_Cadastro')),
                ('proj_para_publicacao', models.BinaryField(blank=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dados_cadastro_penf')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_noticia', models.ImageField(upload_to='', verbose_name='Imagem_Noticia')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dados_cadastro_penf')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_noticia', models.ImageField(upload_to='', verbose_name='Imagem_Noticia')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dados_cadastro_penf')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais_usu')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_Usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereco')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='dados_cadastro_penf',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Cidade_Usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado_usu')),
            ],
        ),
        migrations.CreateModel(
            name='Bairro_Usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade_usu')),
            ],
        ),
        migrations.CreateModel(
            name='Acervo_Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acervos_docs', models.DateTimeField(verbose_name='Data_Acervo_Docs')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('documento', models.BinaryField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
